### ISSUE TITLE
Erro ao consultar uma encomenda que não foi localizada no fluxo postal

### ISSUE THREAD

**Issue by skydomo** [PostmonAPI/postmon#109]
A seguinte chamada produz um erro:
http://api.postmon.com.br/v1/rastreio/ect/PI270740004BR

Abaixo o acesso direto no site dos correios:
http://websro.correios.com.br/sro_bin/txect01$.QueryList?P_LINGUA=001&P_TIPO=001&P_COD_UNI=PI270740004BR

**Comment by duduribeiro** [comment]
@iurisilvio será q precisa gerar uma versão do packtrack no pypi ? 
Eu testei local usando a versão 1.0.2 e quando buscado por esse código gera o seguinte erro:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/site-packages/bottle.py", line 1729, in wrapper
    rv = callback(*a, **ka)
  File "PostmonServer.py", line 159, in track_pack
    encomenda = Correios.track(track)
  File "/usr/local/lib/python2.7/site-packages/packtrack/__init__.py", line 11, in track
    return Correios.encomenda_repository.get(numero)
  File "/usr/local/lib/python2.7/site-packages/packtrack/correios.py", line 8, in get
    return self.correios_website_scraper.get_encomenda_info(numero)
  File "/usr/local/lib/python2.7/site-packages/packtrack/scraping.py", line 20, in get_encomenda_info
    [encomenda.adicionar_status(status) for status in self._get_all_status_from_html(html)]
  File "/usr/local/lib/python2.7/site-packages/packtrack/scraping.py", line 33, in _get_all_status_from_html
    if re.match(r'\d{2}\/\d{2}\/\d{4} \d{2}:\d{2}', tr.contents[0].string):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 141, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or buffer
```

Ao testar usando um clone do packtrack, funciona normalmente.

**Comment by iurisilvio** [comment]
Sim, isso já está corrigido no packtrack. aleborba/packtrack#7

Eu antes tinha criado a #87 e fechei. Fiz errado, já que o bug ainda existe aqui.

Preciso do @aleborba pra atualizar o pacote do packtrack no PyPI.

**Comment by iurisilvio** [comment]
Resolvido provisoriamente com a instalação do packtrack direto do github.

Manter essa issue aberta até o @aleborba resolver o packtrack.

**Comment by iurisilvio** [comment]
Só por email pro ale responder. Consegui gerar uma versão do packtrack (1.0.3) e atualizei tudo que precisava.

Bug finalmente resolvido.
