### ISSUE TITLE
Erro em produção: AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by iurisilvio** [PostmonAPI/postmon#111]
```
2015-04-10 11:20:44,783 - PostmonServer - ERROR - 404 Pacote **** nao encontrado
Traceback (most recent call last):
  File "/var/www/PostmonServer.py", line 159, in track_pack
    encomenda = Correios.track(track)
  File "/usr/local/lib/python2.7/dist-packages/packtrack/__init__.py", line 11, in track
    return Correios.encomenda_repository.get(numero)
  File "/usr/local/lib/python2.7/dist-packages/packtrack/correios.py", line 8, in get
    return self.correios_website_scraper.get_encomenda_info(numero)
  File "/usr/local/lib/python2.7/dist-packages/packtrack/scraping.py", line 20, in get_encomenda_info
    [encomenda.adicionar_status(status) for status in self._get_all_status_from_html(html)]
  File "/usr/local/lib/python2.7/dist-packages/packtrack/scraping.py", line 25, in _get_all_status_from_html
    table = html_info.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by iurisilvio** [comment]
A página usada no site dos correios parou de funcionar. Precisa reimplementar no packtrack.

aleborba/packtrack#9
